title: Viktor Shcherbakov
tagline: Machine Learning Engineer
description: >-
  This is a personal website where I write about my experience, thoughts and share 
  potentially useful information.
url: "https://viktor-shcherb.github.io"
baseurl: ""
logo: /logos-flavicon/flavicon.svg
author: Viktor Shcherbakov
github:
  username: viktor-shcherb
locale: en_US
timezone: "Europe/Zurich"
future: true          # tells Jekyll to publish posts dated in the future

# remove .html from the blog pages
permalink: /:year/:month/:day/:title/

remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-avatar
sass:
  load_paths:
    - assets/css
defaults:
  -
    scope: { path: "" }
    values:
      header: header-custom

feed:
  path: feed.xml
  title: "Viktor Shcherbakov — Blog"
  description: "The theme of the blog is to be defined, but you are welcome to have a look around!"
  lang: en-US
  author_name: Viktor Shcherbakov
  author_url: https://viktor-shcherb.github.io/about/
  full_content: true

