name: PR preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

# needed so the action can push the preview to gh-pages and add comments
permissions:
  contents: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'   # skip the Jekyll build on PR close
    steps:
      # ------------------------------------------------------------------
      # 1 Build static site the same way GitHub Pages does
      # ------------------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        uses: actions/jekyll-build-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      # ------------------------------------------------------------------
      # 2 Deploy preview under pr-preview/pr-<num>/ on gh-pages
      # ------------------------------------------------------------------

      - uses: rossjrw/pr-preview-action@v1
        id: preview-step
        with:
          source-dir: ./_site/
          preview-branch: ${{ env.PREVIEW_BRANCH }}
          comment: false

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.preview-step.outputs.deployment-action == 'deploy' && env.deployment_status == 'success'
        with:
          header: pr-preview
          message: |
            [PR Preview Action](https://github.com/rossjrw/pr-preview-action) ${{ steps.preview-step.outputs.action-version }}
            :---:
            | <p></p> :rocket: View preview at <br> ${{ steps.preview-step.outputs.preview-url }} <br><br>
            | <h6>Built to branch [`${{ env.PREVIEW_BRANCH }}`](${{ github.server_url }}/${{ github.repository }}/tree/${{ env.PREVIEW_BRANCH }}) at ${{ steps.preview-step.outputs.action-start-time }}. <br> Preview will be ready when the [GitHub Pages deployment](${{ github.server_url }}/${{ github.repository }}/deployments) is complete. <br><br> </h6>

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.preview-step.outputs.deployment-action == 'remove' && env.deployment_status == 'success'
        with:
          header: pr-preview
          message: |
            [PR Preview Action](https://github.com/rossjrw/pr-preview-action) ${{ steps.preview-step.outputs.action-version }}
            :---:
            Preview removed because the pull request was closed.
            ${{ steps.preview-step.outputs.action-start-time }}

      # expose the URL to the next job
    outputs:
      preview_url: ${{ steps.preview.outputs.preview-url }}

  lighthouse:
    needs: build-and-preview
    runs-on: ubuntu-latest
    steps:
      - name: Lighthouse audit + PR comment
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: '${{ needs.build-and-preview.outputs.preview_url }},${{ needs.build-and-preview.outputs.preview_url }}/about'
